### ISSUE TITLE
[error] test.sh: 30: Syntax error: "}" unexpected

### ISSUE THREAD

**Issue by ji-junhyuk** [hochan222/rush00-tester#1]
![1](https://user-images.githubusercontent.com/67992469/136684123-b61e7272-c24c-435f-b644-53b6a18082c8.png)
![2](https://user-images.githubusercontent.com/67992469/136684124-a8e327f0-fe2d-4f37-a921-b37d3eeb4563.png)

cd rush00-tester
sh test.sh
실행한 결과 이런 메시지가 나옵니다. 어떻게 수정해야할지 몰라서 여쭤봅니다.
test.sh: 30: Syntax error: "}" unexpected

**Comment by hochan222** [comment]
@ji-junhyuk 님 안녕하세요:) 
 test.sh 파일 첫째줄에 `#!/bin/bash`를 추가하고 한번 다시 해보실 수 있을까요? 제 환경에서는 오류가 나지 않아서, 만약 오류가 난다면 이것 때문일것같긴합니다. 혹시, 그래도 안된다면 gif로 전체 과정을 보여주실 수 있으신가요? 저는 다시 돌려보았는데 [README GIF](https://github.com/hochan222/rush00-tester)와 같이 잘 작동합니다. 
 
 사용해주셔서 감사합니다.

**Comment by ji-junhyuk** [comment]
아 이게 제가 노트북이 윈도우(wsl)이라 안되는 것인가요? 맥 운영체제에서만 되는건지 궁금합니다.

**Comment by ji-junhyuk** [comment]
아!! 친구 맥북으로 해보니 금방 됩니다!
혹시 윈도우로는 왜 안되는지ㅠㅠ

**Comment by hochan222** [comment]
스크립트는 bash 쉘 기준으로 작성했습니다. bash 쉘에서 실행시키면 됩니다!

좋은 하루 보내세요 :)

**Comment by ji-junhyuk** [comment]
집 컴퓨터와 노트북 둘다 bash인데 안됐었는데 방법을 찾았어요.
왜 그런지는 모르겠는데 test.sh 파일에 있는 prompt~makefile 함수에서 
function을 지우고 ()을 열면 되더라고요!

참고)
https://stackoverflow.com/questions/33016331/bash-syntax-error-in-osx

**Comment by hochan222** [comment]
function usage { 이 표준이아니였군요! 알려주셔서 감사합니다 :)
